name: medicine_app
description: Minimal Android client for RxIE prescription scanning.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_document_scanner: ^0.5.0
  google_mlkit_text_recognition: 0.15.1
  http: ^1.6.0
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
