#!/usr/bin/env python3
# ruff: noqa: E402, E501
"""
P8: Sampling Strategy & Imbalance Audit Script for RxIE Pre-Training Sprint.
Analyzes unsealed Train/Validation distributions per prescription.
Locks the standard training sampler and ablation configuration.

Outputs:
  reports/pretraining/sampling_distribution.json
  reports/pretraining/sampling_audit.md
"""

from __future__ import annotations

import json
import statistics
import sys
from collections import Counter
from pathlib import Path
from typing import Any

root_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(root_dir / "src"))

from rxie.schemas import AnnotationDocumentV2


def run_sampling_audit() -> tuple[dict[str, Any], str]:
    dataset_dir = root_dir / "data" / "ner_dataset"
    docs_by_split: dict[str, list[AnnotationDocumentV2]] = {}
    for split in ["train", "val"]:
        f_path = dataset_dir / f"{split}.jsonl"
        docs: list[AnnotationDocumentV2] = []
        if f_path.exists():
            with f_path.open("r", encoding="utf-8") as fp:
                for line in fp:
                    if line.strip():
                        docs.append(AnnotationDocumentV2.model_validate_json(line))
        docs_by_split[split] = docs

    # Distribution stats
    rx_doc_counts: dict[str, int] = Counter()
    rx_ent_counts: dict[str, int] = Counter()
    rx_to_split: dict[str, str] = {}

    for split, docs in docs_by_split.items():
        for d in docs:
            rx_id = d.prescription_id or "UNKNOWN"
            rx_doc_counts[rx_id] += 1
            rx_ent_counts[rx_id] += len(d.entities)
            rx_to_split[rx_id] = split

    all_doc_counts = list(rx_doc_counts.values())
    all_ent_counts = list(rx_ent_counts.values())

    table_rows = []
    for rx_id in sorted(rx_doc_counts.keys()):
        num_docs = rx_doc_counts[rx_id]
        num_ents = rx_ent_counts[rx_id]
        avg_ent = num_ents / num_docs if num_docs > 0 else 0.0
        split_role = rx_to_split.get(rx_id, "train")
        table_rows.append(
            f"| {rx_id:<8} | {split_role:<5} | {num_docs:>15} | {num_ents:>14} | {avg_ent:>18.1f} |"
        )

    table_header = (
        "| RX ID    | Split | # Documents (Cap) | # Total Entities | Avg Entities / Doc |\n"
        "| :------- | :---- | ----------------: | ---------------: | -----------------: |"
    )
    table_body = "\n".join(table_rows)

    md_content = f"""# RxIE Pre-Training Sprint: Sampling & Prescription Imbalance Audit (P8)

## 1. Distribution Summary
- **Total Prescriptions Audited:** {len(rx_doc_counts)}
- **Documents per Prescription:** Min = {min(all_doc_counts)}, Max = {max(all_doc_counts)}, Median = {statistics.median(all_doc_counts):.1f}, Mean = {statistics.mean(all_doc_counts):.1f}
- **Total Entities per Prescription:** Min = {min(all_ent_counts)}, Max = {max(all_ent_counts)}, Median = {statistics.median(all_ent_counts):.1f}

## 2. Per-Prescription Volume Breakdown

{table_header}
{table_body}

## 3. Sampling Policy Freeze for Benchmark V1

### Baseline Policy (Fixed across E0, E1, E2)
- **Sampler:** `Shuffled Token-Window Batching with Single-Loss Ownership`
- **Batch Size:** `8`
- **Random Seeds:** `[42, 3407, 2026]`
- **E0 Expansion:** `279 train documents -> 474 token windows`.
- **Rationale:** All backbones use the same 256-total-input, content-overlap-64 policy. Window counts are reported by the training runner.

### Ablation Policy (Scheduled post-baseline)
- **Sampler:** `PrescriptionWeightedRandomSampler` ($w_i = 1 / N_{{p(i)}}$)
- **Controlled Comparison:** Compare baseline vs weighted sampler exclusively using PhoBERT checkpoint E0.

---
*Generated by `scripts/audit_sampling.py`.*
"""

    report_json = {
        "summary": {
            "total_prescriptions": len(rx_doc_counts),
            "doc_counts_stats": {
                "min": min(all_doc_counts),
                "max": max(all_doc_counts),
                "median": float(statistics.median(all_doc_counts)),
                "mean": float(statistics.mean(all_doc_counts)),
            },
        },
        "per_prescription": {
            rx_id: {
                "split": rx_to_split.get(rx_id, "train"),
                "document_count": rx_doc_counts[rx_id],
                "entity_count": rx_ent_counts[rx_id],
            }
            for rx_id in sorted(rx_doc_counts.keys())
        },
        "locked_sampling_policy": {
            "default_sampler": "DocumentLevelShuffled",
            "ablation_sampler": "PrescriptionWeightedRandomSampler",
            "seeds": [42, 3407, 2026],
        },
    }

    return report_json, md_content


def main() -> None:
    reports_dir = root_dir / "reports" / "pretraining"
    reports_dir.mkdir(parents=True, exist_ok=True)

    json_path = reports_dir / "sampling_distribution.json"
    md_path = reports_dir / "sampling_audit.md"

    report_json, md_content = run_sampling_audit()

    with json_path.open("w", encoding="utf-8") as f:
        json.dump(report_json, f, ensure_ascii=False, indent=2)

    with md_path.open("w", encoding="utf-8") as f:
        f.write(md_content)

    print(f"[+] Exported Sampling Distribution JSON -> {json_path}")
    print(f"[+] Exported Sampling Audit Markdown   -> {md_path}")


if __name__ == "__main__":
    main()
