#!/usr/bin/env python3
"""Seal-safe class trainability audit over Train and Validation only."""

from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

root_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(root_dir / "src"))

from rxie.schemas import AnnotationDocumentV2, EntityType  # noqa: E402


def run_trainability_audit() -> tuple[dict[str, Any], str]:
    dataset_dir = root_dir / "data" / "ner_dataset"
    split_counts: dict[str, Counter[str]] = {
        "train": Counter(),
        "val": Counter(),
    }
    documents_by_class: dict[str, set[str]] = defaultdict(set)
    prescriptions_by_class: dict[str, set[str]] = defaultdict(set)
    surface_forms: dict[str, set[str]] = defaultdict(set)
    document_counts = {}

    for split in ["train", "val"]:
        with (dataset_dir / f"{split}.jsonl").open("r", encoding="utf-8") as handle:
            documents = [
                AnnotationDocumentV2.model_validate_json(line)
                for line in handle
                if line.strip()
            ]
        document_counts[split] = len(documents)
        for document in documents:
            for entity in document.entities:
                entity_type = entity.type.value
                split_counts[split][entity_type] += 1
                documents_by_class[entity_type].add(document.document_id)
                if document.prescription_id:
                    prescriptions_by_class[entity_type].add(document.prescription_id)
                surface_forms[entity_type].add(entity.text.strip())

    classes = [entity_type.value for entity_type in EntityType]
    class_results = {}
    rows = []
    for entity_type in classes:
        result = {
            "train_count": split_counts["train"][entity_type],
            "val_count": split_counts["val"][entity_type],
            "prescription_count": len(prescriptions_by_class[entity_type]),
            "document_count": len(documents_by_class[entity_type]),
            "unique_surface_form_count": len(surface_forms[entity_type]),
        }
        class_results[entity_type] = result
        rows.append(
            f"| {entity_type:<11} | {result['train_count']:>5} | "
            f"{result['val_count']:>3} | {result['prescription_count']:>13} | "
            f"{result['document_count']:>9} | "
            f"{result['unique_surface_form_count']:>12} |"
        )

    report = {
        "scope": "unsealed_train_validation_only",
        "document_counts": document_counts,
        "classes": class_results,
    }
    markdown = "\n".join(
        [
            "# RxIE Trainability-by-Class Audit",
            "",
            "The sealed Test split is intentionally excluded from this "
            "pre-training audit.",
            "",
            f"- Train documents: {document_counts['train']}",
            f"- Validation documents: {document_counts['val']}",
            "",
            "| Class | Train | Val | Prescriptions | Documents | Unique Forms |",
            "| :--- | ---: | ---: | ---: | ---: | ---: |",
            *rows,
            "",
            "Generated by `scripts/audit_trainability_by_class.py`.",
        ]
    )
    return report, markdown + "\n"


def main() -> None:
    report, markdown = run_trainability_audit()
    reports_dir = root_dir / "reports" / "pretraining"
    reports_dir.mkdir(parents=True, exist_ok=True)
    with (reports_dir / "trainability_by_class.json").open(
        "w", encoding="utf-8"
    ) as handle:
        json.dump(report, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    (reports_dir / "trainability_by_class.md").write_text(markdown, encoding="utf-8")
    print("[+] Seal-safe trainability audit complete")


if __name__ == "__main__":
    main()
